### ISSUE TITLE
Improve the messages stored by the Actions Log

### ISSUE THREAD

**Issue by esgg** [fserena/GLORIAServices#1]
It's a good idea to discriminate the messages by its sender and type (device error, warning, etc)

**Comment by fserena** [comment]
I'm going to improve the teleoperation messages first

**Comment by fserena** [comment]
RTSHandler exception messages improved!

**Comment by fserena** [comment]
Teleoperation messages & exceptions have been modified.

**Comment by fserena** [comment]
Teleoperation log entries are now more useful.

**Comment by fserena** [comment]
I am including success messages for teleoperation.

**Comment by fserena** [comment]
All services implements the URL-style log messages now.
I am going to test it a few days more before closing this task.
